# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Storybook CI

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn prestart
    - run: yarn build
    - run: yarn test
    - run: git config --global user.email "aleksoider@gmail.com"
    - run: git config --global user.name "AlexSav94"
    - run: yarn deploy-storybook -- --ci --host-token-env-variable=GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
